server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql://localhost:3306/leyou?useSSL=false&serverTimezone=UTC
    driver: com.mysql.cj.jdbc.Driver
    password: 125809
    username: root
  rabbitmq:
    host: 192.168.17.129
    virtual-host: /
    username: guest
    password: guest
    template:
      exchange: leyou.item.exchange
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
mybatis:
  type-aliases-package: com.leyou.item.pojo